- name: Build Docker Image
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Build and tag Docker image
      community.docker.docker_image:
        name: 66022365:latest
        source: build
        build:
          path: ~/66022365
        state: present
        force_source: true
